// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ZGLIFHuYTCKzdTfFdTfXWMdsHH5wv_s',
    appId: '1:672477751503:web:2c6b92d6ef8faf1aaeafba',
    messagingSenderId: '672477751503',
    projectId: 'analytics-example-e3a62',
    authDomain: 'analytics-example-e3a62.firebaseapp.com',
    storageBucket: 'analytics-example-e3a62.appspot.com',
    measurementId: 'G-EQE02SRCQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlqsqZolPjd8f96pHoT-JK7R14pIUFvw',
    appId: '1:672477751503:android:4a352a1c8db8a335aeafba',
    messagingSenderId: '672477751503',
    projectId: 'analytics-example-e3a62',
    storageBucket: 'analytics-example-e3a62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Ms79OCSqwpwlR5TJq0DbRuKh3NlDt94',
    appId: '1:672477751503:ios:abc3537743d0b6b9aeafba',
    messagingSenderId: '672477751503',
    projectId: 'analytics-example-e3a62',
    storageBucket: 'analytics-example-e3a62.appspot.com',
    androidClientId: '672477751503-4kldlr5m1q95v92ts170pvsle0jgjlck.apps.googleusercontent.com',
    iosClientId: '672477751503-171rqcr6411332p1prm3lr56nb8iamft.apps.googleusercontent.com',
    iosBundleId: 'com.xbr.analyticsExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Ms79OCSqwpwlR5TJq0DbRuKh3NlDt94',
    appId: '1:672477751503:ios:abc3537743d0b6b9aeafba',
    messagingSenderId: '672477751503',
    projectId: 'analytics-example-e3a62',
    storageBucket: 'analytics-example-e3a62.appspot.com',
    androidClientId: '672477751503-4kldlr5m1q95v92ts170pvsle0jgjlck.apps.googleusercontent.com',
    iosClientId: '672477751503-171rqcr6411332p1prm3lr56nb8iamft.apps.googleusercontent.com',
    iosBundleId: 'com.xbr.analyticsExample',
  );
}
